name: Deploy App

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Chọn môi trường triển khai"
        required: true
        default: "staging"
        type: choice
        options:
          - dev
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v4

      - name: In môi trường được chọn
        run: echo "Triển khai đến môi trường: ${{ github.event.inputs.env }}"
